[browser]
gatherUsageStats = false

[server]
headless = true
maxUploadSize = 5

[theme]
primaryColor = "#6f42c1"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"
font = "sans serif"
